# Deprecation Notice

As of May 2022, Red Hat CodeReady Studio has been https://developers.redhat.com/articles/2022/04/18/announcement-red-hat-codeready-studio-reaches-end-life#:~:text=Red%20Hat%20CodeReady%20Studio%20will,of%20the%20JBoss%20Tools%20project.[deprecated].  No further feature development is
expected at this time.

The developers would like to express their sincere gratitude to everyone who has contributed over the
last few years.

= Team Management for git organizations

This repository has team members in <teamname>.team files which then
can be easily added to a team - making it and possible for others to make link:jbdevstudio-teams/README.adoc[pull requests]
to add/remove team members.

= Team management for jira

As a shortcut for adding dev, qe, etc. to jira there are two scripts:

   `addtodev.sh` - adds first argument user to relevant jira groups as an employee working in development
   `addtoqa.sh` - adds  first argument user to relevant jira groups as an employee working in QE

To use this you need to install https://bobswift.atlassian.net/wiki/display/JCLI/JIRA+Command+Line+Interface[Jira CLI]
and setup `jira` to know about your username, password and jira instance.

This is done the simplest by editing the `jira.sh` command in the CLI distribution to include something like this:

`--server https://issues.jboss.org --user maxandersen --password secret`

Note: to add user to groups in jira you must have jira administrator rights.
